export type FieldHelp = { meaning: string; effect?: string; rule?: boolean };

export const fieldHelp: Record<string, FieldHelp> = {
  "Nome personaggio": { meaning: "Nome con cui il personaggio è identificato nell'app." },
  Livello: { meaning: "Livello totale del personaggio.", effect: "Aggiorna il bonus competenza e tutti i calcoli che lo usano, inclusa l'Iniziativa con Allerta.", rule: true },
  Classe: { meaning: "Classe iniziale del personaggio.", effect: "Determina le opzioni di Sottoclasse mostrate; le capacità di classe si registrano separatamente.", rule: true },
  Sottoclasse: { meaning: "Specializzazione della Classe, scelta quando le regole la concedono.", rule: true },
  "Punti Ferita": { meaning: "Punti ferita attuali.", rule: true },
  "Punti Ferita Massimi": { meaning: "Limite ordinario dei punti ferita del personaggio.", rule: true },
  "Classe Armatura": { meaning: "Valore che un tiro per colpire deve raggiungere. La scheda lo calcola da Destrezza, armatura indossata e scudo impugnato.", rule: true },
  Scudo: { meaning: "Indica se il personaggio impugna uno scudo. Con la competenza negli scudi, aggiunge 2 alla Classe Armatura calcolata; una variante magica impugnata aggiunge il suo bonus.", rule: true },
  "Dadi Vita": { meaning: "Dadi Vita del personaggio, da usare per riposo e avanzamento.", rule: true },
  "Punti Esperienza": { meaning: "Esperienza accumulata dal personaggio.", rule: true },
  "Ispirazione Eroica": { meaning: "Risorsa che permette di ritirare un dado secondo le regole 2024.", rule: true },
  "Velocità": { meaning: "Velocità di movimento registrata in metri.", rule: true },
  Allineamento: { meaning: "Descrizione generale dell'orientamento morale del personaggio.", rule: true },
  "Taglia base": { meaning: "Taglia ordinaria determinata dalla Specie; alcune Specie consentono una scelta tra Piccola e Media.", rule: true },
  Specie: { meaning: "Specie del personaggio e origine dei suoi tratti. È una scelta iniziale fissa.", rule: true },
  Background: { meaning: "Origine e occupazione che hanno formato il personaggio prima dell'avventura.", rule: true },
  Lignaggio: { meaning: "Variante prevista da alcune Specie, come Elfo, Gnomo e Tiefling.", rule: true },
  Lingue: { meaning: "Lingue che il personaggio conosce: può usarle per comunicare, leggere e scrivere.", rule: true },
  "Note lingue": { meaning: "Dettagli personali sulle lingue conosciute." },
  Valore: { meaning: "Punteggio di una delle sei caratteristiche.", effect: "Aggiorna il modificatore, i tiri salvezza, le abilità collegate e gli altri calcoli derivati.", rule: true },
  "Valore.FOR": { meaning: "Forza: potenza fisica e capacità di esercitare forza.", effect: "Aggiorna il modificatore di Forza, il suo tiro salvezza e Atletica.", rule: true },
  "Valore.DES": { meaning: "Destrezza: agilità, riflessi e precisione.", effect: "Aggiorna il modificatore di Destrezza, il suo tiro salvezza, le abilità collegate e l'Iniziativa.", rule: true },
  "Valore.COS": { meaning: "Costituzione: salute e resistenza fisica.", effect: "Aggiorna il modificatore e il tiro salvezza di Costituzione; i Punti Ferita Massimi non sono ricalcolati automaticamente.", rule: true },
  "Valore.INT": { meaning: "Intelligenza: memoria e ragionamento.", effect: "Aggiorna il modificatore di Intelligenza, il suo tiro salvezza e le abilità collegate.", rule: true },
  "Valore.SAG": { meaning: "Saggezza: consapevolezza e intuizione.", effect: "Aggiorna il modificatore di Saggezza, il suo tiro salvezza, le abilità collegate e la Percezione Passiva.", rule: true },
  "Valore.CAR": { meaning: "Carisma: presenza e capacità di influenzare gli altri.", effect: "Aggiorna il modificatore di Carisma, il suo tiro salvezza e le abilità collegate.", rule: true },
  "Tiro Salvezza": { meaning: "Indica la competenza nel tiro salvezza della caratteristica.", effect: "Se attiva, il bonus competenza viene aggiunto al tiro salvezza.", rule: true },
  Maestria: { meaning: "Raddoppia il bonus competenza per l'abilità indicata.", effect: "Aggiorna il bonus dell'abilità e, per Percezione, anche la Percezione Passiva.", rule: true },
  "Competenze armi": { meaning: "Armi o categorie di armi in cui il personaggio è competente.", rule: true },
  "Competenze negli strumenti": { meaning: "Classe, background, talenti e altre capacità possono concedere competenza in uno strumento. Si aggiunge il bonus competenza alle prove che usano quello strumento; se si applica anche una competenza in un'abilità, la prova ha vantaggio. Tocca una competenza per vederne l'origine.", rule: true },
  Armi: { meaning: "Armi possedute o usate dal personaggio." },
  "Quantità arma": { meaning: "Numero di esemplari dell'arma posseduti." },
  "Nome arma": { meaning: "Tipo di arma registrata.", rule: true },
  "Bonus att./CD": { meaning: "Bonus al tiro per colpire o CD associata all'arma, se pertinente." },
  "Dettaglio arma": { meaning: "Note personali sull'arma, come proprietà, danni o effetti." },
  "Competenze armatura": { meaning: "Categorie di armatura e scudi che il personaggio sa usare. La competenza negli scudi permette di ottenere il +2 alla Classe Armatura calcolata quando uno scudo è impugnato.", rule: true },
  Oggetti: { meaning: "Equipaggiamento posseduto dal personaggio." },
  Oggetto: { meaning: "Nome di un oggetto posseduto." },
  "Dettaglio oggetto": { meaning: "Dettaglio personale di un oggetto." },
  Privilegi: { meaning: "Privilegi e capacità ottenuti da classe, specie o altre fonti.", rule: true },
  Titolo: { meaning: "Nome del privilegio o della capacità." },
  "Scelte privilegio": { meaning: "Scelte e dettagli personali legati a un privilegio." },
  Talenti: { meaning: "Talenti acquisiti dal personaggio.", effect: "Il talento Allerta aumenta automaticamente l'Iniziativa; gli altri effetti vanno registrati dove pertinenti.", rule: true },
  "Nome talento": { meaning: "Talento selezionato per il personaggio.", effect: "Allerta aggiunge il bonus competenza all'Iniziativa; gli altri effetti non sono tutti automatici.", rule: true },
  "Scelte talento": { meaning: "Scelte personali richieste o concesse dal talento.", rule: true },
  Incantesimi: { meaning: "Incantesimi registrati nella scheda.", rule: true },
  "Nome incantesimo": { meaning: "Nome dell'incantesimo scelto dal catalogo.", rule: true },
  Monete: { meaning: "Quantità possedute per ciascun tipo di moneta.", rule: true },
};

export function helpFor(id: string): FieldHelp | null {
  return fieldHelp[id] ?? null;
}
