// Equipaggiamento d'avventura, Manuale del Giocatore 2024, tabella a p. 223.
// I pesi non indicati dalla fonte restano assenti.
// Gli ID storici srd52 restano stabili per leggere le schede già salvate;
// nomi, pesi e costi visualizzati sono confrontati con il Manuale locale.
export type GearContent = { name: string; quantity?: number };
export type Gear = { id: string; name: string; weightKg?: number; costGp?: number; priceQuantity?: number; sourcePage?: number; contents?: GearContent[]; tool?: boolean; toolKind?: "artigiano" | "gioco" | "musicale" | "altro" };

// Contenuti delle dotazioni, Manuale del Giocatore 2024, p. 225.
const packContents: Record<string, GearContent[]> = {
  "dotazione-avventuriero": [{ name: "Zaino" }, { name: "Triboli" }, { name: "Piede di porco" }, { name: "Olio", quantity: 2 }, { name: "Razioni", quantity: 10 }, { name: "Corda" }, { name: "Acciarino e pietra focaia" }, { name: "Torcia", quantity: 10 }, { name: "Otre" }],
  "dotazione-diplomatico": [{ name: "Forziere" }, { name: "Abiti eleganti" }, { name: "Inchiostro" }, { name: "Pennino", quantity: 5 }, { name: "Lampada" }, { name: "Custodia per mappe o pergamene", quantity: 2 }, { name: "Olio", quantity: 4 }, { name: "Carta", quantity: 5 }, { name: "Pergamena", quantity: 5 }, { name: "Profumo" }, { name: "Acciarino e pietra focaia" }],
  "dotazione-esploratore": [{ name: "Zaino" }, { name: "Giaciglio" }, { name: "Olio", quantity: 2 }, { name: "Razioni", quantity: 10 }, { name: "Corda" }, { name: "Acciarino e pietra focaia" }, { name: "Torcia", quantity: 10 }, { name: "Otre" }],
  "dotazione-intrattenitore": [{ name: "Zaino" }, { name: "Giaciglio" }, { name: "Campanella" }, { name: "Lanterna a lente sporgente" }, { name: "Costume", quantity: 3 }, { name: "Specchio" }, { name: "Olio", quantity: 8 }, { name: "Razioni", quantity: 9 }, { name: "Otre" }],
  "dotazione-sacerdote": [{ name: "Zaino" }, { name: "Coperta" }, { name: "Acqua santa" }, { name: "Lampada" }, { name: "Razioni", quantity: 7 }, { name: "Tunica" }, { name: "Acciarino e pietra focaia" }],
  "dotazione-scassinatore": [{ name: "Zaino" }, { name: "Sfere metalliche" }, { name: "Campanella" }, { name: "Candela", quantity: 10 }, { name: "Piede di porco" }, { name: "Lanterna schermabile" }, { name: "Olio", quantity: 7 }, { name: "Razioni", quantity: 5 }, { name: "Corda" }, { name: "Acciarino e pietra focaia" }, { name: "Otre" }],
  "dotazione-studioso": [{ name: "Zaino" }, { name: "Libro" }, { name: "Inchiostro" }, { name: "Pennino" }, { name: "Lampada" }, { name: "Olio", quantity: 10 }, { name: "Pergamena", quantity: 10 }, { name: "Acciarino e pietra focaia" }],
};

const rows: [string, string, number | null, number][] = [
  ["abiti-viaggiatore", "Abiti da viaggiatore", 2, 2],
  ["abiti-eleganti", "Abiti eleganti", 3, 15],
  ["acciarino", "Acciarino e pietra focaia", 0.5, 0.5],
  ["acido", "Acido", 0.5, 25],
  ["acqua-santa", "Acqua santa", 0.5, 25],
  ["ampolla", "Ampolla", 0.5, 0.02],
  ["antitossina", "Antitossina", null, 50],
  ["ariete-portatile", "Ariete portatile", 17.5, 4],
  ["asta", "Asta", 3.5, 0.05],
  ["attrezzi-scalatore", "Attrezzi da scalatore", 6, 25],
  ["barile", "Barile", 35, 2],
  ["borsa", "Borsa", 0.5, 0.5],
  ["borsa-guaritore", "Borsa del guaritore", 1.5, 5],
  ["borsa-componenti", "Borsa per componenti", 1, 25],
  ["bottiglia-vetro", "Bottiglia di vetro", 1, 2],
  ["brocca", "Brocca", 2, 0.02],
  ["campanella", "Campanella", null, 1],
  ["candela", "Candela", null, 0.01],
  ["cannocchiale", "Cannocchiale", 0.5, 1000],
  ["carrucola-paranco", "Carrucola e paranco", 2.5, 1],
  ["carta", "Carta", null, 0.2],
  ["catena", "Catena", 5, 5],
  ["cesto", "Cesto", 1, 0.4],
  ["coperta", "Coperta", 1.5, 0.5],
  ["corda", "Corda", 2.5, 1],
  ["costume", "Costume", 2, 5],
  ["custodia-mappe", "Custodia per mappe o pergamene", 0.5, 1],
  ["custodia-quadrelli", "Custodia per quadrelli da balestra", 0.5, 1],
  ["dotazione-avventuriero", "Dotazione da avventuriero", 27.5, 12],
  ["dotazione-diplomatico", "Dotazione da diplomatico", 19.5, 39],
  ["dotazione-esploratore", "Dotazione da esploratore", 27.5, 10],
  ["dotazione-intrattenitore", "Dotazione da intrattenitore", 29, 40],
  ["dotazione-sacerdote", "Dotazione da sacerdote", 14, 33],
  ["dotazione-scassinatore", "Dotazione da scassinatore", 19, 16],
  ["dotazione-studioso", "Dotazione da studioso", 11, 40],
  ["faretra", "Faretra", 0.5, 1],
  ["fiala", "Fiala", null, 1],
  ["fischietto", "Fischietto da richiamo", null, 0.05],
  ["forziere", "Forziere", 12.5, 5],
  ["fuoco-alchimista", "Fuoco dell'alchimista", 0.5, 50],
  ["giaciglio", "Giaciglio", 3.5, 1],
  ["inchiostro", "Inchiostro", null, 10],
  ["lampada", "Lampada", 0.5, 0.5],
  ["lanterna-lente", "Lanterna a lente sporgente", 1, 10],
  ["lanterna-schermabile", "Lanterna schermabile", 1, 5],
  ["lente-ingrandimento", "Lente d'ingrandimento", null, 100],
  ["libro", "Libro", 2.5, 25],
  ["manette", "Manette", 3, 2],
  ["mappa", "Mappa", null, 1],
  ["olio", "Olio", 0.5, 0.1],
  ["otre", "Otre", 2.5, 0.2],
  ["pala", "Pala", 2.5, 2],
  ["pennino", "Pennino", null, 0.02],
  ["pentola-ferro", "Pentola di ferro", 5, 2],
  ["pergamena", "Pergamena", null, 0.1],
  ["pergamena-livello-1", "Pergamena magica (livello 1)", null, 50],
  ["pergamena-trucchetto", "Pergamena magica (trucchetto)", null, 30],
  ["piede-porco", "Piede di porco", 2.5, 2],
  ["pozione-guarigione", "Pozione di guarigione", 0.25, 50],
  ["profumo", "Profumo", null, 5],
  ["rampino", "Rampino", 2, 2],
  ["razioni", "Razioni", 1, 0.5],
  ["rete", "Rete", 1.5, 1],
  ["sacco", "Sacco", 0.25, 0.01],
  ["scala-pioli", "Scala a pioli", 12.5, 0.1],
  ["secchio", "Secchio", 1, 0.05],
  ["serratura", "Serratura", 0.5, 10],
  ["sfere-metalliche", "Sfere metalliche", 1, 1],
  ["spago", "Spago", null, 0.1],
  ["specchio", "Specchio", 0.25, 5],
  ["spuntoni-ferro", "Spuntoni di ferro", 2.5, 1],
  ["tagliola", "Tagliola", 12.5, 5],
  ["tenda", "Tenda", 10, 2],
  ["torcia", "Torcia", 0.5, 0.01],
  ["triboli", "Triboli", 1, 1],
  ["tunica", "Tunica", 2, 1],
  ["veleno-base", "Veleno base", null, 100],
  ["zaino", "Zaino", 2.5, 2],
];

export const gearCatalog: Gear[] = rows.map(([id, name, weightKg, costGp]) => ({
  id: `srd52:gear:${id}`, name, ...(weightKg === null ? {} : { weightKg }), costGp,
  ...(packContents[id] ? { contents: packContents[id], sourcePage: 225 } : {}),
}));
// Manuale del Giocatore 2024, tabella Focus druidici: la voce generale ha costo variabile.
gearCatalog.push(
  { id: "phb24:gear:focus-arcano", name: "Focus arcano", sourcePage: 225 },
  { id: "phb24:gear:focus-arcano-bacchetta", name: "Focus arcano (bacchetta)", weightKg: 0.5, costGp: 10, sourcePage: 225 },
  { id: "phb24:gear:focus-arcano-bastone", name: "Focus arcano (bastone)", weightKg: 2, costGp: 5, sourcePage: 225 },
  { id: "phb24:gear:focus-arcano-cristallo", name: "Focus arcano (cristallo)", weightKg: 0.5, costGp: 10, sourcePage: 225 },
  { id: "phb24:gear:focus-arcano-globo", name: "Focus arcano (globo)", weightKg: 1.5, costGp: 20, sourcePage: 225 },
  { id: "phb24:gear:focus-arcano-verga", name: "Focus arcano (verga)", weightKg: 1, costGp: 10, sourcePage: 225 },
  { id: "phb24:gear:focus-druidico", name: "Focus druidico", sourcePage: 225 },
  { id: "phb24:gear:focus-druidico-bacchetta-tasso", name: "Focus druidico (bacchetta in legno di tasso)", weightKg: 0.5, costGp: 10, sourcePage: 225 },
  { id: "phb24:gear:focus-druidico-bastone-legno", name: "Focus druidico (bastone di legno)", weightKg: 2, costGp: 5, sourcePage: 225 },
  { id: "phb24:gear:focus-druidico-rametto-vischio", name: "Focus druidico (rametto di vischio)", costGp: 1, sourcePage: 225 },
  { id: "phb24:gear:simbolo-sacro", name: "Simbolo sacro", sourcePage: 228 },
  { id: "phb24:gear:simbolo-sacro-amuleto", name: "Simbolo sacro (amuleto)", weightKg: 0.5, costGp: 5, sourcePage: 228 },
  { id: "phb24:gear:simbolo-sacro-emblema", name: "Simbolo sacro (emblema)", costGp: 5, sourcePage: 228 },
  { id: "phb24:gear:simbolo-sacro-reliquiario", name: "Simbolo sacro (reliquiario)", weightKg: 1, costGp: 5, sourcePage: 228 },
);
// La tabella Munizioni (p. 226) dà peso e prezzo per confezione.
gearCatalog.push(
  { id: "srd52:ammo:aghi", name: "Aghi", weightKg: 0.5 / 50, costGp: 1, priceQuantity: 50 },
  { id: "srd52:ammo:frecce", name: "Frecce", weightKg: 0.5 / 20, costGp: 1, priceQuantity: 20 },
  { id: "srd52:ammo:proiettili-arma-fuoco", name: "Proiettili per arma da fuoco", weightKg: 1 / 10, costGp: 3, priceQuantity: 10 },
  { id: "srd52:ammo:proiettili-fionda", name: "Proiettili per fionda", weightKg: 0.75 / 20, costGp: 0.04, priceQuantity: 20 },
  { id: "srd52:ammo:quadrelli", name: "Quadrelli", weightKg: 0.75 / 20, costGp: 1, priceQuantity: 20 },
);
const tools: [string, string, number | null, number][] = [
  ["scorte-alchimista", "Scorte da alchimista", 4, 50],
  ["scorte-birraio", "Scorte da birraio", 4.5, 20],
  ["scorte-calligrafo", "Scorte da calligrafo", 2.5, 10],
  ["strumenti-calzolaio", "Strumenti da calzolaio", 2.5, 5],
  ["strumenti-cartografo", "Strumenti da cartografo", 3, 15],
  ["strumenti-conciatore", "Strumenti da conciatore", 2.5, 5],
  ["strumenti-fabbro", "Strumenti da fabbro", 4, 20],
  ["strumenti-falegname", "Strumenti da falegname", 3, 8],
  ["strumenti-gioielliere", "Strumenti da gioielliere", 1, 25],
  ["strumenti-intagliatore", "Strumenti da intagliatore", 2.5, 1],
  ["strumenti-inventore", "Strumenti da inventore", 5, 50],
  ["strumenti-muratore", "Strumenti da muratore", 4, 10],
  ["strumenti-pittore", "Strumenti da pittore", 2.5, 10],
  ["strumenti-soffiatore", "Strumenti da soffiatore", 2.5, 30],
  ["strumenti-tessitore", "Strumenti da tessitore", 2.5, 1],
  ["strumenti-vasaio", "Strumenti da vasaio", 1.5, 10],
  ["utensili-cuoco", "Utensili da cuoco", 4, 1],
  ["arnesi-falsario", "Arnesi da falsario", 2.5, 15],
  ["arnesi-scasso", "Arnesi da scasso", 0.5, 25],
  ["borsa-erborista", "Borsa da erborista", 1.5, 5],
  ["sostanze-avvelenatore", "Sostanze da avvelenatore", 1, 50],
  ["strumenti-navigatore", "Strumenti da navigatore", 1, 25],
  ["trucchi-camuffamento", "Trucchi per il camuffamento", 1.5, 25],
];
gearCatalog.push(...tools.map(([id, name, weightKg, costGp], index): Gear => ({ id: `srd52:tool:${id}`, name, ...(weightKg === null ? {} : { weightKg }), costGp, sourcePage: index < 11 ? 220 : 221, tool: true, toolKind: index < 17 ? "artigiano" : "altro" })));
// Le varianti di gioco e strumento musicale richiedono competenze distinte (p. 221).
gearCatalog.push(
  { id: "phb24:tool:gioco-dadi", name: "Dadi", costGp: 0.1, sourcePage: 221, tool: true, toolKind: "gioco" },
  { id: "phb24:tool:gioco-scacchi-dei-draghi", name: "Scacchi dei draghi", costGp: 1, sourcePage: 221, tool: true, toolKind: "gioco" },
  { id: "phb24:tool:gioco-carte-da-gioco", name: "Carte da gioco", costGp: 0.5, sourcePage: 221, tool: true, toolKind: "gioco" },
  { id: "phb24:tool:gioco-tre-draghi-al-buio", name: "Tre Draghi al Buio", costGp: 1, sourcePage: 221, tool: true, toolKind: "gioco" },
  { id: "phb24:tool:musicale-cornamusa", name: "Cornamusa", weightKg: 3, costGp: 30, sourcePage: 221, tool: true, toolKind: "musicale" },
  { id: "phb24:tool:musicale-tamburo", name: "Tamburo", weightKg: 1.5, costGp: 6, sourcePage: 221, tool: true, toolKind: "musicale" },
  { id: "phb24:tool:musicale-dulcimer", name: "Dulcimer", weightKg: 5, costGp: 25, sourcePage: 221, tool: true, toolKind: "musicale" },
  { id: "phb24:tool:musicale-flauto", name: "Flauto", weightKg: 0.5, costGp: 2, sourcePage: 221, tool: true, toolKind: "musicale" },
  { id: "phb24:tool:musicale-flauto-di-pan", name: "Flauto di pan", weightKg: 1, costGp: 12, sourcePage: 221, tool: true, toolKind: "musicale" },
  { id: "phb24:tool:musicale-ciaramella", name: "Ciaramella", weightKg: 0.5, costGp: 2, sourcePage: 221, tool: true, toolKind: "musicale" },
  { id: "phb24:tool:musicale-corno", name: "Corno", weightKg: 1, costGp: 3, sourcePage: 221, tool: true, toolKind: "musicale" },
  { id: "phb24:tool:musicale-liuto", name: "Liuto", weightKg: 1, costGp: 35, sourcePage: 221, tool: true, toolKind: "musicale" },
  { id: "phb24:tool:musicale-lira", name: "Lira", weightKg: 1, costGp: 30, sourcePage: 221, tool: true, toolKind: "musicale" },
  { id: "phb24:tool:musicale-viola", name: "Viola", weightKg: 0.5, costGp: 30, sourcePage: 221, tool: true, toolKind: "musicale" },
);
export const gearById = (id: string): Gear | undefined => gearCatalog.find((item) => item.id === id);
export const gearByName = (name: string): Gear | undefined => gearCatalog.find((item) => item.name === name);
