// Equipaggiamento d'avventura, SRD 5.2.1 italiano, tabella a p. 107.
// I pesi non indicati dalla fonte restano assenti.
export type Gear = { id: string; name: string; weightKg?: number; costGp?: number; priceQuantity?: number; sourcePage?: number; tool?: boolean };

const rows: [string, string, number | null, number][] = [
  ["abiti-viaggiatore", "Abiti da viaggiatore", 2, 2],
  ["abiti-eleganti", "Abiti eleganti", 3, 15],
  ["acciarino", "Acciarino e pietra focaia", 0.5, 0.5],
  ["acido", "Acido", 0.5, 25],
  ["acqua-santa", "Acqua santa", 0.5, 25],
  ["ampolla", "Ampolla", 0.5, 0.02],
  ["antitossina", "Antitossina", null, 50],
  ["ariete-portatile", "Ariete portatile", 17.5, 4],
  ["asta", "Asta", 3.5, 0.05],
  ["attrezzi-scalatore", "Attrezzi da scalatore", 6, 25],
  ["barile", "Barile", 35, 2],
  ["borsa", "Borsa", 0.5, 0.5],
  ["borsa-guaritore", "Borsa del guaritore", 1.5, 5],
  ["borsa-componenti", "Borsa per componenti", 1, 25],
  ["bottiglia-vetro", "Bottiglia di vetro", 1, 2],
  ["brocca", "Brocca", 2, 0.02],
  ["campanella", "Campanella", null, 1],
  ["candela", "Candela", null, 0.01],
  ["cannocchiale", "Cannocchiale", 0.5, 1000],
  ["carrucola-paranco", "Carrucola e paranco", 2.5, 1],
  ["carta", "Carta", null, 0.2],
  ["catena", "Catena", 5, 5],
  ["cesto", "Cesto", 1, 0.4],
  ["coperta", "Coperta", 1.5, 0.5],
  ["corda", "Corda", 2.5, 1],
  ["costume", "Costume", 2, 5],
  ["custodia-mappe", "Custodia per mappe o pergamene", 0.5, 1],
  ["custodia-quadrelli", "Custodia per quadrelli da balestra", 0.5, 1],
  ["dotazione-avventuriero", "Dotazione da avventuriero", 27.5, 12],
  ["dotazione-diplomatico", "Dotazione da diplomatico", 19.5, 39],
  ["dotazione-esploratore", "Dotazione da esploratore", 27.5, 10],
  ["dotazione-intrattenitore", "Dotazione da intrattenitore", 29, 40],
  ["dotazione-sacerdote", "Dotazione da sacerdote", 14, 33],
  ["dotazione-scassinatore", "Dotazione da scassinatore", 19, 16],
  ["dotazione-studioso", "Dotazione da studioso", 11, 40],
  ["faretra", "Faretra", 0.5, 1],
  ["fiala", "Fiala", null, 1],
  ["fischietto", "Fischietto da richiamo", null, 0.05],
  ["forziere", "Forziere", 12.5, 5],
  ["fuoco-alchimista", "Fuoco dell'alchimista", 0.5, 50],
  ["giaciglio", "Giaciglio", 3.5, 1],
  ["inchiostro", "Inchiostro", null, 10],
  ["lampada", "Lampada", 0.5, 0.5],
  ["lanterna-lente", "Lanterna a lente sporgente", 1, 10],
  ["lanterna-schermabile", "Lanterna schermabile", 1, 5],
  ["lente-ingrandimento", "Lente d'ingrandimento", null, 100],
  ["libro", "Libro", 2.5, 25],
  ["manette", "Manette", 3, 2],
  ["mappa", "Mappa", null, 1],
  ["olio", "Olio", 0.5, 0.1],
  ["otre", "Otre", 2.5, 0.2],
  ["pala", "Pala", 2.5, 2],
  ["pennino", "Pennino", null, 0.02],
  ["pentola-ferro", "Pentola di ferro", 5, 2],
  ["pergamena", "Pergamena", null, 0.1],
  ["pergamena-livello-1", "Pergamena magica (livello 1)", null, 50],
  ["pergamena-trucchetto", "Pergamena magica (trucchetto)", null, 30],
  ["piede-porco", "Piede di porco", 2.5, 2],
  ["pozione-guarigione", "Pozione di guarigione", 0.25, 50],
  ["profumo", "Profumo", null, 5],
  ["rampino", "Rampino", 2, 2],
  ["razioni", "Razioni", 1, 0.5],
  ["rete", "Rete", 1.5, 1],
  ["sacco", "Sacco", 0.25, 0.01],
  ["scala-pioli", "Scala a pioli", 12.5, 0.1],
  ["secchio", "Secchio", 1, 0.05],
  ["serratura", "Serratura", 0.5, 10],
  ["sfere-metalliche", "Sfere metalliche", 1, 1],
  ["spago", "Spago", null, 0.1],
  ["specchio", "Specchio", 0.25, 5],
  ["spuntoni-ferro", "Spuntoni di ferro", 2.5, 1],
  ["tagliola", "Tagliola", 12.5, 5],
  ["tenda", "Tenda", 10, 2],
  ["torcia", "Torcia", 0.5, 0.01],
  ["triboli", "Triboli", 1, 1],
  ["tunica", "Tunica", 2, 1],
  ["veleno-base", "Veleno base", null, 100],
  ["zaino", "Zaino", 2.5, 2],
];

export const gearCatalog: Gear[] = rows.map(([id, name, weightKg, costGp]) => ({ id: `srd52:gear:${id}`, name, ...(weightKg === null ? {} : { weightKg }), costGp }));
// Manuale del Giocatore 2024, tabella Focus druidici: la voce generale ha costo variabile.
gearCatalog.push(
  { id: "phb24:gear:focus-druidico", name: "Focus druidico", sourcePage: 225 },
  { id: "phb24:gear:focus-druidico-bacchetta-tasso", name: "Focus druidico (bacchetta in legno di tasso)", weightKg: 0.5, costGp: 10, sourcePage: 225 },
  { id: "phb24:gear:focus-druidico-bastone-legno", name: "Focus druidico (bastone di legno)", weightKg: 2, costGp: 5, sourcePage: 225 },
  { id: "phb24:gear:focus-druidico-rametto-vischio", name: "Focus druidico (rametto di vischio)", costGp: 1, sourcePage: 225 },
);
// La tabella Munizioni (p. 110) dà peso e prezzo per confezione.
gearCatalog.push(
  { id: "srd52:ammo:aghi", name: "Aghi", weightKg: 0.5 / 50, costGp: 1, priceQuantity: 50 },
  { id: "srd52:ammo:frecce", name: "Frecce", weightKg: 0.5 / 20, costGp: 1, priceQuantity: 20 },
  { id: "srd52:ammo:proiettili-arma-fuoco", name: "Proiettili per arma da fuoco", weightKg: 1 / 10, costGp: 3, priceQuantity: 10 },
  { id: "srd52:ammo:proiettili-fionda", name: "Proiettili per fionda", weightKg: 0.75 / 20, costGp: 0.4, priceQuantity: 20 },
  { id: "srd52:ammo:quadrelli", name: "Quadrelli", weightKg: 0.75 / 20, costGp: 1, priceQuantity: 20 },
);
const tools: [string, string, number | null, number][] = [
  ["scorte-alchimista", "Scorte da alchimista", 4, 50],
  ["scorte-birraio", "Scorte da birraio", 4.5, 20],
  ["scorte-calligrafo", "Scorte da calligrafo", 2.5, 10],
  ["strumenti-calzolaio", "Strumenti da calzolaio", 2.5, 5],
  ["strumenti-cartografo", "Strumenti da cartografo", 3, 15],
  ["strumenti-conciatore", "Strumenti da conciatore", 2.5, 5],
  ["strumenti-fabbro", "Strumenti da fabbro", 4, 20],
  ["strumenti-falegname", "Strumenti da falegname", 3, 8],
  ["strumenti-gioielliere", "Strumenti da gioielliere", 1, 25],
  ["strumenti-intagliatore", "Strumenti da intagliatore", 2.5, 1],
  ["strumenti-inventore", "Strumenti da inventore", 5, 50],
  ["strumenti-muratore", "Strumenti da muratore", 4, 10],
  ["strumenti-pittore", "Strumenti da pittore", 2.5, 10],
  ["strumenti-soffiatore", "Strumenti da soffiatore", 2.5, 30],
  ["strumenti-tessitore", "Strumenti da tessitore", 2.5, 1],
  ["strumenti-vasaio", "Strumenti da vasaio", 1.5, 10],
  ["utensili-cuoco", "Utensili da cuoco", 4, 1],
  ["arnesi-falsario", "Arnesi da falsario", 2.5, 15],
  ["arnesi-scasso", "Arnesi da scasso", 0.5, 25],
  ["borsa-erborista", "Borsa da erborista", 1.5, 5],
  ["sostanze-avvelenatore", "Sostanze da avvelenatore", 1, 50],
  ["strumenti-navigatore", "Strumenti da navigatore", 1, 25],
  ["trucchi-camuffamento", "Trucchi per il camuffamento", 1.5, 25],
];
gearCatalog.push(...tools.map(([id, name, weightKg, costGp]) => ({ id: `srd52:tool:${id}`, name, ...(weightKg === null ? {} : { weightKg }), costGp, sourcePage: 105, tool: true })));
export const gearById = (id: string): Gear | undefined => gearCatalog.find((item) => item.id === id);
export const gearByName = (name: string): Gear | undefined => gearCatalog.find((item) => item.name === name);
