import Link from "next/link";
import { asc, desc, eq } from "drizzle-orm";
import { db } from "@/lib/db";
import { characters, creatures, masterSessionCreatures, masterSessionEvents, masterSessionParticipants, masterSessions } from "@/lib/db/schema";
import { closeMasterSession, createMasterSession, saveMasterParticipants } from "./actions";
import { MasterCharacterCard, MasterCreatureCard, RestPanel } from "./MasterControls";

export const dynamic = "force-dynamic";

const dateLabel = (date: string) => new Intl.DateTimeFormat("it-IT", { dateStyle: "long", timeZone: "UTC" }).format(new Date(`${date}T12:00:00Z`));
const timeLabel = (date: Date) => new Intl.DateTimeFormat("it-IT", { timeStyle: "short" }).format(date);
const eventLabel = (type: string) => ({
  sessione_creata: "Sessione creata", partecipanti_aggiornati: "Partecipanti aggiornati", sessione_chiusa: "Sessione chiusa",
  riposo_breve_gruppo: "Riposo breve del gruppo", riposo_lungo_gruppo: "Riposo lungo del gruppo",
}[type] ?? type.replaceAll("_", " "));

export default async function MasterPage({ searchParams }: { searchParams?: Promise<{ errore?: string }> }) {
  const query = searchParams ? await searchParams : {};
  const [people, creatureList, openSessions, closedSessions, events] = await Promise.all([
    db.select({ id: characters.id, name: characters.name, data: characters.data }).from(characters).orderBy(asc(characters.name)),
    db.select({ id: creatures.id, name: creatures.name, data: creatures.data }).from(creatures).orderBy(asc(creatures.name)),
    db.select().from(masterSessions).where(eq(masterSessions.status, "aperta")).limit(1),
    db.select().from(masterSessions).where(eq(masterSessions.status, "chiusa")).orderBy(desc(masterSessions.closedAt)),
    db.select().from(masterSessionEvents).orderBy(desc(masterSessionEvents.occurredAt)),
  ]);
  const active = openSessions[0];
  const activeParticipantRows = active ? await db.select({ characterId: masterSessionParticipants.characterId }).from(masterSessionParticipants).where(eq(masterSessionParticipants.sessionId, active.id)) : [];
  const activeParticipantIds = new Set(activeParticipantRows.map(({ characterId }) => characterId));
  const activeCreatureRows = active ? await db.select({ creatureId: masterSessionCreatures.creatureId }).from(masterSessionCreatures).where(eq(masterSessionCreatures.sessionId, active.id)) : [];
  const activeCreatureIds = new Set(activeCreatureRows.map(({ creatureId }) => creatureId));
  const party = people.map((person) => ({ ...person, data: person.data }));
  const restCharacters = people.map((person) => ({ ...person, isSessionParticipant: activeParticipantIds.has(person.id) }));
  const restCreatures = creatureList.map((creature) => ({ ...creature, isSessionParticipant: activeCreatureIds.has(creature.id) }));

  return <main className="mx-auto flex min-h-dvh w-full max-w-3xl flex-col gap-6 px-4 py-6 sm:px-6">
    <header className="flex items-center"><Link href="/" aria-label="Torna alla home" className="flex min-h-11 items-center gap-1.5 text-left text-ink"><span className="text-lg leading-none text-ink-soft" aria-hidden>⌂</span><h1 className="text-base font-bold">Master</h1></Link></header>
    {query.errore && <p role="alert" className="rounded-xl border border-red-300 bg-red-50 px-4 py-3 text-sm font-medium text-red-900">{query.errore}</p>}
    {active ? <section className="rounded-2xl border border-accent/50 bg-card p-4 shadow-sm sm:p-6" aria-labelledby="active-session-title">
      <div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-sm font-semibold uppercase tracking-wide text-accent">Sessione aperta</p><h2 id="active-session-title" className="mt-1 text-xl font-bold text-ink">{active.name}</h2><p className="text-sm text-ink-soft">{dateLabel(active.localDate)}</p></div><form action={closeMasterSession}><input type="hidden" name="sessionId" value={active.id} /><button className="min-h-11 rounded-xl border border-line px-4 font-semibold text-ink">Chiudi Sessione</button></form></div>
      <form action={saveMasterParticipants} className="mt-5 border-t border-line pt-4"><input type="hidden" name="sessionId" value={active.id} /><fieldset><legend className="mb-3 font-semibold text-ink">Partecipanti</legend><div className="grid grid-cols-1 gap-2 sm:grid-cols-2">{people.map((person) => <label key={person.id} className="flex min-h-12 items-center gap-3 rounded-xl border border-line px-3 py-2 text-ink"><input type="checkbox" name="participant" value={person.id} defaultChecked={activeParticipantIds.has(person.id)} className="size-5 accent-accent" /><span>{person.name}</span></label>)}</div>{creatureList.length > 0 && <div className="mt-4 grid grid-cols-1 gap-2 sm:grid-cols-2">{creatureList.map((creature) => <label key={creature.id} className="flex min-h-12 items-center gap-3 rounded-xl border border-line px-3 py-2 text-ink"><input type="checkbox" name="creature" value={creature.id} defaultChecked={activeCreatureIds.has(creature.id)} className="size-5 accent-accent" /><span>{creature.name} <span className="text-xs text-ink-soft">(creatura)</span></span></label>)}</div>}</fieldset><button className="mt-4 min-h-11 w-full rounded-xl bg-accent px-4 font-bold text-white">Salva partecipanti</button></form>
      <section className="mt-5 border-t border-line pt-4"><h3 className="mb-3 font-semibold text-ink">Riposi</h3><div className="grid gap-3 sm:grid-cols-2"><RestPanel sessionId={active.id} kind="breve" characters={restCharacters} creatures={restCreatures} /><RestPanel sessionId={active.id} kind="lungo" characters={restCharacters} creatures={restCreatures} /></div></section>
      <section className="mt-5 border-t border-line pt-4"><h3 className="mb-3 font-semibold text-ink">Personaggi</h3><div className="grid gap-3 sm:grid-cols-2">{people.map((person) => <MasterCharacterCard key={person.id} sessionId={active.id} character={person} party={party} canAct={activeParticipantIds.has(person.id)} />)}</div></section>
      {creatureList.length > 0 && <section className="mt-5 border-t border-line pt-4"><h3 className="mb-3 font-semibold text-ink">Creature</h3><div className="grid gap-3 sm:grid-cols-2">{creatureList.map((creature) => <MasterCreatureCard key={creature.id} sessionId={active.id} creature={creature} canAct={activeCreatureIds.has(creature.id)} />)}</div></section>}
      <section className="mt-5 border-t border-line pt-4" aria-labelledby="events-title"><h3 id="events-title" className="font-semibold text-ink">Eventi</h3><ol className="mt-2 flex flex-col gap-2">{events.filter((event) => event.sessionId === active.id).map((event) => <li key={event.id} className="rounded-lg bg-card/70 px-3 py-2 text-sm text-ink"><time className="mr-2 text-ink-soft">{timeLabel(event.occurredAt)}</time>{eventLabel(event.type)}</li>)}</ol></section>
    </section> : <details className="rounded-2xl border border-line bg-card p-4 shadow-sm sm:p-6"><summary className="min-h-12 cursor-pointer list-none rounded-xl bg-accent px-4 py-3 text-center font-bold text-white">Nuova sessione</summary><form action={createMasterSession} className="mt-5"><label htmlFor="session-name" className="mb-2 block font-semibold text-ink">Nome della Sessione</label><input id="session-name" name="name" required maxLength={120} className="min-h-12 w-full rounded-xl border border-line bg-white px-3 text-base text-ink" /><fieldset className="mt-5"><legend className="mb-3 font-semibold text-ink">Personaggi partecipanti</legend><div className="grid grid-cols-1 gap-2 sm:grid-cols-2">{people.map((person) => <label key={person.id} className="flex min-h-12 items-center gap-3 rounded-xl border border-line px-3 py-2 text-ink"><input type="checkbox" name="participant" value={person.id} defaultChecked className="size-5 accent-accent" /><span>{person.name}</span></label>)}</div>{creatureList.length > 0 && <div className="mt-4 grid grid-cols-1 gap-2 sm:grid-cols-2">{creatureList.map((creature) => <label key={creature.id} className="flex min-h-12 items-center gap-3 rounded-xl border border-line px-3 py-2 text-ink"><input type="checkbox" name="creature" value={creature.id} defaultChecked className="size-5 accent-accent" /><span>{creature.name} <span className="text-xs text-ink-soft">(creatura)</span></span></label>)}</div>}{!people.length && <p className="text-sm text-ink-soft">Nessun personaggio: la Sessione può essere creata e aggiornata in seguito.</p>}</fieldset><button className="mt-5 min-h-12 w-full rounded-xl bg-accent px-4 font-bold text-white">Crea Sessione</button></form></details>}
    <section aria-labelledby="archive-title"><h2 id="archive-title" className="mb-3 text-lg font-bold text-ink">Sessioni concluse</h2>{closedSessions.length ? <ul className="flex flex-col gap-2">{closedSessions.map((session) => <li key={session.id} className="rounded-xl border border-line bg-card/70 px-4 py-3"><details><summary className="flex cursor-pointer list-none items-center justify-between gap-3"><span><span className="block font-semibold text-ink">{session.name}</span><span className="text-sm text-ink-soft">{dateLabel(session.localDate)}</span></span><span className="shrink-0 text-sm text-ink-soft">Chiusa</span></summary><ol className="mt-3 flex flex-col gap-2 border-t border-line pt-3">{events.filter((event) => event.sessionId === session.id).map((event) => <li key={event.id} className="text-sm text-ink"><time className="mr-2 text-ink-soft">{new Intl.DateTimeFormat("it-IT", { dateStyle: "short", timeStyle: "short" }).format(event.occurredAt)}</time>{eventLabel(event.type)}</li>)}</ol></details></li>)}</ul> : <p className="rounded-xl border border-line bg-card/60 px-4 py-5 text-sm text-ink-soft">Nessuna Sessione archiviata.</p>}</section>
  </main>;
}
